services:
  neo4j:
    image: 'neo4j:latest'
    ports:
      - "7474:7474"    # HTTP
      - "7687:7687"    # Bolt
    environment:
      - 'NEO4J_AUTH=neo4j/notverysecret'
      - 'NEO4J_dbms_default__database=resources-database'
