### Created Detached Resource
< {%
    client.global.set("B2", $random.uuid.toString())
%}
POST http://localhost:8080/register-detached
Content-Type: application/json

{
  "id": "{{B2}}",
  "name": "B2",
  "projectId": "{{project_id}}",
  "additionalLabels": ["B", "BaseResource"]
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

### Created Neighbor Resources
< {%
    client.global.set("S1p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S1p}}",
    "name": "S1p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S2p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S2p}}",
    "name": "S2p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E1p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S1p}}",
  "neighbor": {
    "id": "{{E1p}}",
    "name": "E1p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E2p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S2p}}",
  "neighbor": {
    "id": "{{E2p}}",
    "name": "E2p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S3p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S3p}}",
    "name": "S3p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S4p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S4p}}",
    "name": "S4p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S5p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S5p}}",
    "name": "S5p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S6p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{S6p}}",
    "name": "S6p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E3p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S3p}}",
  "neighbor": {
    "id": "{{E3p}}",
    "name": "E3p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E4p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S4p}}",
  "neighbor": {
    "id": "{{E4p}}",
    "name": "E4p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E5p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S5p}}",
  "neighbor": {
    "id": "{{E5p}}",
    "name": "E5p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E6p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S6p}}",
  "neighbor": {
    "id": "{{E6p}}",
    "name": "E6p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("M1p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{M1p}}",
    "name": "M1p",
    "additionalLabels": ["M"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("M2p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B2}}",
  "neighbor": {
    "id": "{{M2p}}",
    "name": "M2p",
    "additionalLabels": ["M"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S7p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{M1p}}",
  "neighbor": {
    "id": "{{S7p}}",
    "name": "S7p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("S8p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{M2p}}",
  "neighbor": {
    "id": "{{S8p}}",
    "name": "S8p",
    "additionalLabels": ["S"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E7p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S7p}}",
  "neighbor": {
    "id": "{{E7p}}",
    "name": "E7p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}

###
< {%
    client.global.set("E8p", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S8p}}",
  "neighbor": {
    "id": "{{E8p}}",
    "name": "E8p",
    "additionalLabels": ["E"],
    "relationshipContext": "default",
    "relationshipType": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 201", function () {
        console.log(request.body())
        client.assert(response.status === 201, "Expected status code is 201")
    });
%}