### Created Detached Resource
< {%
    client.global.set("B3", $random.uuid.toString())
%}
POST http://localhost:8080/register-detached
Content-Type: application/json

{
  "id": "{{B3}}",
  "name": "B3",
  "projectId": "{{project_id}}",
  "additionalLabels": ["B"]
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E1pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{E1pp}}",
    "name": "E1pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E2pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{E2pp}}",
    "name": "E2pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}


### Created Neighbor Resources
< {%
    client.global.set("S1pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{S1pp}}",
    "name": "S1pp",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S2pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{S2pp}}",
    "name": "S2pp",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S3pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{S3pp}}",
    "name": "S3pp",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E3pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S1pp}}",
  "neighbor": {
    "id": "{{E3pp}}",
    "name": "E3pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E4pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S2pp}}",
  "neighbor": {
    "id": "{{E4pp}}",
    "name": "E4pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E5pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S3pp}}",
  "neighbor": {
    "id": "{{E5pp}}",
    "name": "E5pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S1ppR", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S1pp}}",
  "neighbor": {
    "id": "{{S1ppR}}",
    "name": "S1ppR",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "REPUSH_OF"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E3ppR", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S1ppR}}",
  "neighbor": {
    "id": "{{E3ppR}}",
    "name": "E3ppR",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S2ppR", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S2pp}}",
  "neighbor": {
    "id": "{{S2ppR}}",
    "name": "S2ppR",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "REPUSH_OF"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E4ppR", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S2ppR}}",
  "neighbor": {
    "id": "{{E4ppR}}",
    "name": "E4ppR",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("M1pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{M1pp}}",
    "name": "M1pp",
    "labels": ["M"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("M2pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{B3}}",
  "neighbor": {
    "id": "{{M2pp}}",
    "name": "M2pp",
    "labels": ["M"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S4pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{M1pp}}",
  "neighbor": {
    "id": "{{S4pp}}",
    "name": "S4pp",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("S5pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{M2pp}}",
  "neighbor": {
    "id": "{{S5pp}}",
    "name": "S5pp",
    "labels": ["S"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E6pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S4pp}}",
  "neighbor": {
    "id": "{{E6pp}}",
    "name": "E6pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E7pp", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{S5pp}}",
  "neighbor": {
    "id": "{{E7pp}}",
    "name": "E7pp",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "CREATED_UNDER"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}

###
< {%
    client.global.set("E1ppR", $random.uuid.toString())
%}
POST http://localhost:8080/register-neighbor
Content-Type: application/json

{
  "projectId": "{{project_id}}",
  "targetResourceId": "{{E1pp}}",
  "neighbor": {
    "id": "{{E1ppR}}",
    "name": "E1ppR",
    "labels": ["E"],
    "relationshipContext": "default",
    "relationshipLabel": "REPUSH_OF"
  }
}

> {%
    client.test("Status code is 200", function () {
        console.log(request.body())
        client.assert(response.status === 200, "Expected status code is 200")
    });
%}