MATCH (t:Resource {id: $targetResourceId})
MATCH (t)-[:CREATED_UNDER*1..$ancestorsGenerationLimit]->(ancestor)
MATCH (ancestor)<-[:CREATED_UNDER*1..$relativesGenerationLimit]-(relative)
  WHERE any(label IN labels(relative) WHERE label IN $relativeResourcesTypeFilter)
RETURN collect(DISTINCT ancestor) + collect(DISTINCT relative)